### ISSUE TITLE
futex_wait issue

### ISSUE THREAD

**Issue by wheelq** [lavv17/lftp#187]
Every now and then, we can see the following issue:

```
Process 10999 attached - interrupt to quit
futex(0x7fdb3bfac2fc, FUTEX_WAIT_PRIVATE, 2, NULL^C <unfinished ...>
```

```
cat /proc/10999/syscall
202 0x7fdb3bfac2fc 0x80 0x2 0x0 0x0 0x2af7 0x7fff45bc0fb0 0x7fdb3bd35e6e
```

this results in thread getting stuck

**Comment by lavv17** [comment]
lftp itself does not use threads. Please run "pstack PID" where PID is the process number of lftp to find out who called that futex function.

**Comment by wheelq** [comment]
well the gstack provides the following output:

```
#0  0x00007fdb3bd35e6e in ?? () from /lib64/libc.so.6
#1  0x00007fdb3bcd0c61 in ?? () from /lib64/libc.so.6
#2  0x00007fdb3bcd0258 in ?? () from /lib64/libc.so.6
#3  0x000000000049f035 in xmalloc(unsigned long) ()
#4  0x000000000049fbbd in xstring::get_space2(unsigned long, unsigned long) ()
#5  0x00000000004a0709 in xstring::nset(char const*, int) ()
#6  0x000000000048d1a5 in ProcWait::proc_key(int) ()
#7  0x000000000048d224 in ProcWait::SIGCHLD_handler(int) ()
#8  <signal handler called>
#9  0x00007fdb3bccaa85 in ?? () from /lib64/libc.so.6
#10 0x00007fdb3bcf8f77 in fork () from /lib64/libc.so.6
#11 0x0000000000501d75 in Resolver::Do() ()
#12 0x000000000048c278 in SMTask::Roll(SMTask*) ()
#13 0x00000000004ff1a3 in NetAccess::Resolve(char const*, char const*, char const*) ()
#14 0x00000000004dd3e3 in Ftp::Do() ()
#15 0x000000000048c311 in SMTask::ScheduleThis() ()
#16 0x000000000048c825 in SMTask::ScheduleNew() ()
#17 0x000000000048c8b3 in SMTask::Schedule() ()
#18 0x000000000044657d in Job::WaitDone() ()
#19 0x0000000000441755 in main ()
```

and gdb:

```
Reading symbols from /lib64/libz.so.1...(no debugging symbols found)...done.
Loaded symbols for /lib64/libz.so.1
Reading symbols from /usr/lib64/libssl.so.0.9.8...(no debugging symbols found)...done.
Loaded symbols for /usr/lib64/libssl.so.0.9.8
Reading symbols from /usr/lib64/libcrypto.so.0.9.8...(no debugging symbols found)...done.
Loaded symbols for /usr/lib64/libcrypto.so.0.9.8
Reading symbols from /lib64/librt.so.1...(no debugging symbols found)...done.
Loaded symbols for /lib64/librt.so.1
Reading symbols from /lib64/libreadline.so.5...(no debugging symbols found)...done.
Loaded symbols for /lib64/libreadline.so.5
Reading symbols from /lib64/libutil.so.1...(no debugging symbols found)...done.
Loaded symbols for /lib64/libutil.so.1
Reading symbols from /lib64/libncurses.so.5...(no debugging symbols found)...done.
Loaded symbols for /lib64/libncurses.so.5
Reading symbols from /lib64/libdl.so.2...(no debugging symbols found)...done.
Loaded symbols for /lib64/libdl.so.2
Reading symbols from /usr/lib64/libstdc++.so.6...(no debugging symbols found)...done.
Loaded symbols for /usr/lib64/libstdc++.so.6
Reading symbols from /lib64/libm.so.6...(no debugging symbols found)...done.
Loaded symbols for /lib64/libm.so.6
Reading symbols from /lib64/libgcc_s.so.1...(no debugging symbols found)...done.
Loaded symbols for /lib64/libgcc_s.so.1
Reading symbols from /lib64/libc.so.6...(no debugging symbols found)...done.
Loaded symbols for /lib64/libc.so.6
Reading symbols from /lib64/libpthread.so.0...(no debugging symbols found)...done.
[Thread debugging using libthread_db enabled]
Loaded symbols for /lib64/libpthread.so.0
Reading symbols from /lib64/ld-linux-x86-64.so.2...(no debugging symbols found)...done.
Loaded symbols for /lib64/ld-linux-x86-64.so.2
(no debugging symbols found)
0x00007fdb3bd35e6e in ?? () from /lib64/libc.so.6
```

**Comment by lavv17** [comment]
It seems it is necessary to avoid any dynamic memory allocations in signal handlers. I'll try to implement a solution.

**Comment by lavv17** [comment]
Please try this patch.
[patch-sigchld.txt](https://github.com/lavv17/lftp/files/8431/patch-sigchld.txt)

**Comment by wheelq** [comment]
sorry for getting back so late. am already using own patch, but today I will try yours. please give it couple days

**Comment by wheelq** [comment]
Still the same. Will recompile and check on a new box.

```
futex(0x7f74f3ce72fc, FUTEX_WAIT_PRIVATE, 2, NULL
```

**Comment by lavv17** [comment]
Let's try another approach. Please revert previous patch and apply this.
[sigchld-count.txt](https://github.com/lavv17/lftp/files/11773/sigchld-count.txt)

**Comment by wheelq** [comment]
so far so good

**Comment by lavv17** [comment]
committed 978cdc8
