### ISSUE TITLE
lftp 4.8.2 segfault

### ISSUE THREAD

**Issue by tomsommer** [lavv17/lftp#400]
```
Program received signal SIGSEGV, Segmentation fault.
0x00000000004a94a5 in Timer::~Timer() ()
Missing separate debuginfos, use: debuginfo-install expat-2.0.1-13.el6_8.x86_64 glibc-2.12-1.209.el6_9.2.x86_64 gnutls-2.12.23-21.el6.x86_64 libgcc-4.4.7-18.el6.x86_64 libgcrypt-1.4.5-12.el6_8.x86_64 libgpg-error-1.7-4.el6.x86_64 libidn2-2.0.4-1.el6.x86_64 libstdc++-4.4.7-18.el6.x86_64 libtasn1-2.3-6.el6_5.x86_64 libunistring-0.9.3-5.el6.x86_64 ncurses-libs-5.7-4.20090207.el6.x86_64 readline-6.0-4.el6.x86_64 zlib-1.2.3-29.el6.x86_64
(gdb) bt full
#0  0x00000000004a94a5 in Timer::~Timer() ()
No symbol table info available.
#1  0x00000000004f01aa in xmap_p<NetAccess::SiteData>::~xmap_p() ()
No symbol table info available.
#2  0x00007ffff5f30992 in exit () from /lib64/libc.so.6
No symbol table info available.
#3  0x00007ffff5f19d24 in __libc_start_main () from /lib64/libc.so.6
No symbol table info available.
#4  0x000000000043e119 in _start ()
No symbol table info available.

```

**Comment by tomsommer** [comment]
Same as #393
