### ISSUE TITLE
SIGSEGV with DHT enabled with run out of listening ports

### ISSUE THREAD

**Issue by kucharskim** [lavv17/lftp#511]
Hi,

This is on OpenBSD 6.4-current (2019-02-16 snapshot), but I believe problem is system independent.

```
$ lftp --version | sed -n '1p;/Libraries/,$p'
LFTP | Version 4.8.4 | Copyright (c) 1996-2017 Alexander V. Lukyanov                                                                
Libraries used: Expat 2.2.6, idn2 2.0.0, libiconv 1.14, OpenSSL LibreSSL 2.9.0,                                                     
Readline 7.0, zlib 1.2.3
```

It's related to the fact that I've started lftp(1) in the same way multiple times (via my own script) and didn't had any instance locking, so I ended up with:

```
$ pgrep -x lftp |  wc -l
       9
```

Command was started as follows:

```
lftp --norc -c 'torrent --dht-bootstrap=dht.transmissionbt.com OpenBSD_6.4_amd64_install64.iso-2018-10-17-2046.torrent'
```

Torrent file is really irrelevant here, but you get the idea. So, with debug command it looks like this:

```
$ time lftp --norc -c 'debug; torrent --dht-bootstrap=dht.transmissionbt.com OpenBSD_6.4_amd64_install64.iso-2018-10-17-2046.torrent'
---- found IPv6 address: 2001:41d0:1:9845::
---- Retrieving meta-data from `/home/00-torrent-test/OpenBSD_6.4_amd64_install64.iso-2018-10-17-2046.torrent'...
---- Resolving host address...
**** bind([0.0.0.0]:6887): Address already in use
**** bind([::]:6883): Address already in use
**** bind([0.0.0.0]:6883): Address already in use
**** bind([::]:6883): Address already in use
**** bind([0.0.0.0]:6883): Address already in use
**** bind([::]:6887): Address already in use
---- meta-data EOF
initialized translation from UTF-8 to US-ASCII//TRANSLIT
initialized translation from UTF-8 to US-ASCII//TRANSLIT
---- Tracker URL is `http://OpenBSD.somedomain.net:6969/announce'
---- Piece length is 262144
---- Total length is 359696384
**** bind([0.0.0.0]:6887): Address already in use
**** open(//.local/share/lftp/torrent/md/3A4B1A8A18D59F6E7F0F7A2BA29EB54E177BF612): No such file or directory
---- opening /home/00-torrent-test/OpenBSD_6.4_amd64_install64.iso
**** bind([::]:6889): Address already in use
**** bind([0.0.0.0]:6889): Address already in use
**** bind([0.0.0.0]:6886): Address already in use
**** bind([::]:6886): Address already in use
**** bind([0.0.0.0]:6886): Address already in use
...
**** bind([0.0.0.0]:6888): Address already in use
**** bind([::]:6887): Address already in use
**** bind([0.0.0.0]:6887): Address already in use
**** bind([::]:6887): Address already in use
---> http://OpenBSD.somedomain.net:6969/announce?info_hash=:K%1A%8A%18%D5%9Fn%7F%0Fz%2B%A2%9E%B5N%17%7B%F6%12&peer_id=-lftp47-9cb25c7
8f57a&port=6887&uploaded=0&downloaded=0&left=359696384&compact=1&no_peer_id=1&event=started&ipv6=[2001:41d0:1:9845::]:6882&numwant=30
&key=5d4d4b079771f11e2134
---- starting search for 3A4B1A8A18D59F6E7F0F7A2BA29EB54E177BF612
---- too few good nodes found in the routing table
**** no nodes found in the routing table
---- starting search for 3A4B1A8A18D59F6E7F0F7A2BA29EB54E177BF612
---- too few good nodes found in the routing table
**** no nodes found in the routing table
---- Resolving host address...
**** bind([0.0.0.0]:6887): Address already in use
**** bind([::]:6881): Address already in use
**** bind([0.0.0.0]:6881): Address already in use
**** bind([::]:6881): Address already in use
**** bind([0.0.0.0]:6881): Address already in use
**** bind([::]:6889): Address already in use
**** bind([0.0.0.0]:6889): Address already in use
**** bind([::]:6889): Address already in use
**** bind([0.0.0.0]:6889): Address already in use
**** bind([::]:6886): Address already in use
---- 3 addresses found: 2001:41d0:c:5ac:5::1, 212.129.33.59, 87.98.162.88
**** bind([0.0.0.0]:6886): Address already in use
**** bind([::]:6886): Address already in use
Segmentation fault (core dumped)
    0m01.23s real     0m00.37s user     0m00.57s system
```

From gdb it looks like this:

```
$ egdb lftp lftp.core
GNU gdb (GDB) 7.12.1
...
Reading symbols from lftp...done.
[New process 229045]
Core was generated by `lftp'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x000002f9dd414643 in __fd_set (fd=<optimized out>, p=<optimized out>) at /usr/include/sys/select.h:81
81              p->fds_bits[fd / __NFDBITS] |= (1U << (fd % __NFDBITS));
(gdb) directory "/data/03-lftp-sources/src:$cdir:$cwd"
Source directories searched: /data/03-lftp-sources/src:$cdir:$cwd
(gdb) bt
#0  0x000002f9dd414643 in __fd_set (fd=<optimized out>, p=<optimized out>) at /usr/include/sys/select.h:81
#1  PollVec::AddFD (this=0x2f9dd5824f8 <SMTask::block>, fd=-1, mask=4) at PollVec.cc:43
#2  0x000002f9dd545832 in SMTask::Block (fd=-1, mask=4) at ./SMTask.h:84
#3  TorrentListener::MaySendUDP (this=0x2fc58b1e800) at Torrent.cc:3916
#4  0x000002f9dd54de6e in DHT::MaySendMessage (this=<optimized out>) at DHT.cc:292
#5  DHT::Do (this=<optimized out>) at DHT.cc:213
#6  0x000002f9dd415556 in SMTask::ScheduleThis (this=0x2fbf3f2f000) at SMTask.cc:209
#7  0x000002f9dd415365 in SMTask::Schedule () at SMTask.cc:248
#8  0x000002f9dd4c17ea in Job::WaitDone (this=0x2fcdb142000) at Job.cc:557
#9  0x000002f9dd404e16 in main (argc=<optimized out>, argv=0x7f7ffffdbf08) at lftp.cc:590
(gdb) list PollVec.cc:43
38      void PollVec::AddFD(int fd,int mask)
39      {
40         if(mask&IN)
41            FD_SET(fd,&in);
42         if(mask&OUT)
43            FD_SET(fd,&out);
44         if(nfds<=fd)
45            nfds=fd+1;
46      }
47      bool PollVec::FDReady(int fd,int mask)
(gdb) list Torrent.cc:3916
3911       pfd.events=POLLOUT;
3912       pfd.revents=0;
3913       int res=poll(&pfd,1,0);
3914       if(res>0)
3915          return true;
3916       Block(sock,POLLOUT);
3917       return false;
3918    }
3919    int TorrentListener::SendUDP(const sockaddr_u& a,const xstring& buf)
3920    {
(gdb) list DHT.cc:292
287        }
288     }
289     bool DHT::MaySendMessage()
290     {
291        return rate_limit.BytesAllowedToPut()>=256
292           && Torrent::GetUDPSocket(af)->MaySendUDP();
293     }
294     void DHT::SendPing(const sockaddr_u& a,const xstring& id)
295     {
296        if(a.port()==0 || a.is_private() || a.is_reserved() || a.is_multicast())
(gdb) list DHT.cc:213
208           if(u.proto==0 && u.host)
209              resolver=new Resolver(u.host,u.port,"6881");
210           m=MOVED;
211        }
212
213        while(send_queue.count()>0 && MaySendMessage()) {
214           SendMessage(send_queue.next().borrow());
215           m=MOVED;
216        }
217
(gdb)
```

This version above has also included 1f22423244c3867fec745cf0c04cd636e10970a2 patch. This is what I found so far. I didn't had chance to test latest commit from repo, but used only OpenBSD ports framework to cherry pick above commit, to see does it help. If you need any more info please let me know. Reproduce of the problem should be easy per above steps, just enough background lftp(1) instances is enough to exhaust ports to bind.

**Comment by kucharskim** [comment]
Tested lftp(1) from commit 8f501af8c96f2bf17e33bfe879b3243fba2bae3a and segmentation fault is still there.

**Comment by lavv17** [comment]
should be fixed in https://github.com/lavv17/lftp/commit/66426abe60ef0f8a1be905f171b1281c6b59d138
