### ISSUE TITLE
http-get testcase fails in AIX

### ISSUE THREAD

**Issue by ayappanec** [lavv17/lftp#542]
I am porting lftp-4.8.4 in AIX operating system. 
As part of the build, i ran make check and the testcase "http-get" failed with IOT/Abort trap. 

<a href="lftp-4.8.4.tar.gz.asc">lftp-4.8.4.tar.gz.asc</a>                              01-Aug-2018 08:33                 155
<a href="lftp-4.8.4.tar.xz">lftp-4.8.4.tar.xz</a>                                  01-Aug-2018 08:33             1633444
<a href="lftp-4.8.4.tar.xz.asc">lftp-4.8.4.tar.xz.asc</a>                              01-Aug-2018 08:33                 155
</pre><hr></body>
</html>
<---

Assertion failed: __EX, file  xheap.h, line 127
IOT/Abort trap(coredump)

Running gdb on the core shows this.

 gdb ./http-get core
GNU gdb (GDB) 8.1.1
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "powerpc64-ibm-aix6.1.0.0".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./http-get...done.

warning: core file may not match specified executable file.
[New Thread 1]
Core was generated by `http-get'.
Program terminated with signal SIGABRT, Aborted.
#0  0x090000000052deb4 in pthread_kill () from /usr/lib/libpthreads.a(shr_xpg5_64.o)
[Current thread is 1 (process 1)]
(gdb) where
#0  0x090000000052deb4 in pthread_kill () from /usr/lib/libpthreads.a(shr_xpg5_64.o)
#1  0x090000000052d6ec in _p_raise () from /usr/lib/libpthreads.a(shr_xpg5_64.o)
#2  0x090000000002bdd0 in raise () from /usr/lib/libc.a(shr_64.o)
#3  0x0900000000082868 in abort () from /usr/lib/libc.a(shr_64.o)
#4  0x09000000000826a8 in __assert_c99 () from /usr/lib/libc.a(shr_64.o)
#5  0x00000001000361f0 in xheap<Timer>::remove (this=<incomplete type>, x=...) at Timer.cc:127
#6  0x0000000100032428 in Timer::~Timer (this=<incomplete type>) at Timer.cc:133
#7  0x00000001000ee6d4 in NetAccess::SiteData::~SiteData (this=<incomplete type>) at ftpclass.cc:31
#8  0x00000001000ee634 in xmap_p<NetAccess::SiteData>::dispose (this=<incomplete type>, p=0x1100707d0) at ftpclass.cc:107
#9  0x000000010012426c in xmap_p<NetAccess::SiteData>::~xmap_p (this=<incomplete type>) at NetAccess.cc:112
#10 0x0900000006fb3df0 in __new_exitfn () from /opt/freeware/lib/pthread/ppc64/libgcc_s.a(shr.o)
#11 0x22244228e0ddf00d in ?? ()
#12 0x000000010013904c in _GLOBAL__FD_http_get ()
#13 0x09fffffff0002668 in mod_fini1 () from /usr/ccs/bin/usla64
#14 0x09fffffff000345c in usl_fini_mods () from /usr/ccs/bin/usla64
#15 0x09fffffff0003230 in usl_exit_fini_mods () from /usr/ccs/bin/usla64
#16 0x0900000000000974 in __modfini64 () from /usr/lib/libc.a(shr_64.o)
#17 0x0900000000037660 in exit () from /usr/lib/libc.a(shr_64.o)
#18 0x00000001000002cc in __start ()
(gdb) 

What would have possibly went wrong ?

**Comment by arberx** [comment]
Any luck with debugging/solving this?

**Comment by ayappanec** [comment]
Didn't get time to look into this. Will check it soon.
