### ISSUE TITLE
lftp core dumps at startup on FreeBSD 11.3-RELEASE-p5

### ISSUE THREAD

**Issue by martymac** [lavv17/lftp#565]
Hi,

lftp core dumps at startup on FreeBSD 11.3-RELEASE-p5 i386 and amd64.

The compiler on that platform is :

FreeBSD clang version 8.0.0 (tags/RELEASE_800/final 356365) (based on LLVM 8.0.0)

From what I understand, global variables from network.cc (which leads to calling NetworkInit::NetworkInit() constructor that triggers the problem) seem to be initialized *before* types_by_name gets instanciated.

Here is a backtrace of the problem :

```
(gdb) run
Starting program: /usr/local/bin/lftp 

Program received signal SIGSEGV, Segmentation fault.
_xmap::make_hash (this=0x0, s=...) at xmap.cc:54
54         if(hash_size==1)
(gdb) bt
#0  _xmap::make_hash (this=0x0, s=...) at xmap.cc:54
#1  0x0814adbe in _xmap::_lookup_c (this=0x0, key=...) at xmap.cc:81
#2  0x0812fd95 in xmap<ResType*>::lookup (this=0x0, key=...) at ./xmap.h:86
#3  0x0812f2f3 in xmap<ResType*>::lookup (this=0x0, key=0x8231b30 "dns:order") at ./xmap.h:91
#4  0x0812b156 in ResType::FindVar (name=0x8231b30 "dns:order", type=0xffffcd08, re_closure=0xffffcd28) at ResMgr.cc:89
#5  0x0812f3f4 in ResType::FindVar (name=0x8231b30 "dns:order", type=0xffffcd08, re_closure=0xffffcd28) at ./ResMgr.h:78
#6  0x0812b4f5 in ResType::Set (name=0x8231b30 "dns:order", cclosure=0x0, cvalue=0x8231b40 "inet", def=false) at ResMgr.cc:159
#7  0x0821f144 in NetworkInit::NetworkInit (this=0x8242a74 <NETWORK_INIT>) at network.cc:485
#8  0x0821f0e2 in __cxx_global_var_init () at network.cc:478
#9  0x0821f1d8 in _GLOBAL__sub_I_network.cc () at ./network.h:106
#10 0x08222c82 in __do_global_ctors_aux ()
#11 0x080a2105 in _init ()
#12 0x2824037f in ?? () from /libexec/ld-elf.so.1
#13 0x2823f5c6 in ?? () from /libexec/ld-elf.so.1
#14 0x2823d12e in ?? () from /libexec/ld-elf.so.1
```

You can find more information about that problem on FreeBSD's Bugzilla :

https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=243307

Thanks in advance,
Best regards,

Ganael.

**Comment by lavv17** [comment]
fixed in 5d344937d60380341c20409c11f135afb630d7ee
