### ISSUE TITLE
Segmentation fault with simple lftpget example

### ISSUE THREAD

**Issue by mxmlnkn** [lavv17/lftp#735]
`gdb -ex r -ex bt --args sh $( which lftpget ) sftp://127.0.0.1:22:silesia.tar.gz .`

Backtrace:

```
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff793ffd5 in __strstr_sse2 (haystack=0x55555573d640 "file name missed in URL", needle=0x0) at ../string/strstr.c:82
82	../string/strstr.c: No such file or directory.
#0  0x00007ffff793ffd5 in __strstr_sse2 (haystack=0x55555573d640 "file name missed in URL", needle=0x0) at ../string/strstr.c:82
#1  0x00005555555c8697 in CopyJob::Do() ()
#2  0x00005555555ffb16 in SMTask::ScheduleThis() ()
#3  0x0000555555604141 in SMTask::Schedule() ()
#4  0x00005555555a6096 in Job::WaitDone() ()
#5  0x000055555559fc84 in main ()
```

Based on the backtrace, it seems that I am using the command wrong? But the manual for lftpget is **very** sparse. An example would be nice.

The correct call seems to be `lftpget sftp://127.0.0.1:22:/home/user/silesia.tar.gz`. I have not found any possibility to specify a relative path. That would have been nice.

**Comment by chengyechun** [comment]
I think you should try lftpget sftp://127.0.0.1:22/home/user/silesia.tar.gz
